name: Deploy to App Hosting
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2.1.3'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: 'Install Firebase CLI'
        run: npm install -g firebase-tools

      - name: 'Deploy to Firebase App Hosting'
        run: firebase apphosting:rollouts:create forgeai --git-branch ${{ github.ref_name }} --project studio-774665260-80d2e
