name: Deploy to App Hosting
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: 'actions/checkout@v4'
      - name: A simple step to see if workflow runs
        run: echo "The basic workflow ran successfully."
